title: "Skokie: A Centennial History"
baseurl: ""
collections:
  chapters:
    output: true
    permalink: /chapters/:title/
defaults:
  -
    scope:
      path: ""
      type: "chapters"
    values:
      layout: "page"
      type: "chapter"
