title: "Skokie: A Centennial History"
baseurl: ""
hostname: "http://skokiecentennialbook.com"
collections:
  chapters:
    output: true
    permalink: /chapters/:title/
defaults:
  -
    scope:
      path: ""
      type: "chapters"
    values:
      layout: "page"
